### ISSUE TITLE
Polish not working

### ISSUE THREAD

**Issue by pstawinski** [leodido/treetagger.docker#5] opened 2016-06-10 07:15 UTC
Hello,

treetagging for Polish is not working:

```
echo 'To jest test.' |         docker run -i leodido/treetagger tree-tagger-polish
/usr/local/cmd/tree-tagger-polish: line 18: /tmp/HS/Tagger/cmd/utf8-tokenize.perl: not found
/usr/local/cmd/tree-tagger-polish: line 18: /tmp/HS/Tagger/bin/tree-tagger: not found
```

while other examples are:

```
echo 'I am going home right now.' |         docker run -i leodido/treetagger tree-tagger-english
        reading parameters ...
        tagging ...
         finished.
I       PP      I
am      VBP     be
going   VBG     go
home    NN      home
right   RB      right
now     RB      now
.       SENT    .
```

**Comment by leodido** [comment] 2017-01-10 02:08
Hi @pstawinski this is not a bug of the docker image.
Unfortunately it is a bug of the `tree-tagger-polish` script which has hard-coded paths ...

I could fix this rebuilding this image with a workaround to patch such file but I think it's simply better to switch to the (upcoming) 3.2.1 tag which will contain that source code already fixed up.

Closing for now.

**Comment by leodido** [comment] 2017-01-10 02:11
See yourself with the following command:

`docker run -i leodido/treetagger cat /usr/local/cmd/tree-tagger-polish`

Which results in ...

```bash
#!/bin/sh

# Set these paths appropriately (Really? LoL)

BIN=/tmp/HS/Tagger/bin
CMD=/tmp/HS/Tagger/cmd
LIB=/tmp/HS/Tagger/lib

# ....
```

**Closed as completed by leodido** 2017-01-10 02:11 UTC
Labels: wontfix
